version : '3.7'

services:
    app:
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                GRAPHICS: "${GRAPHICS:-overcooked_graphics_v1.js}"
                CERTPATH: "${CERTPATH:-/etc/letsencrypt/live/human-agent-collaboration.su.domains}"
        environment:
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - "443:5000"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
